[package]
name = "tupai"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[features]
# Target family features
arch_family_x86 = ["driver_vga"]

# Target arch features
arch_target_i386 = []
arch_target_x86_64 = []

# Driver features
driver_vga = []

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
volatile = "0.1.0"
spin = "0.4.5"

[dependencies.lazy_static]
version = "0.2.1"
features = ["spin_no_std"]
