[package]
name = "tupai"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[features]
# Target family features
arch_family_x86 = ["driver_video_vga"]
arch_family_arm = ["driver_serial", "board_bcm2386", "driver_video_bcm2836"] # Raspberry Pi 2

# Target arch features
arch_target_i386 = []
arch_target_x86_64 = []

arch_target_armv7 = []
arch_target_armv8 = []

# Board features
board_bcm2386 = []

# Driver features
driver_video_vga = []
driver_video_bcm2836 = []

driver_serial = []

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
volatile = "0.1.0"
spin = "0.4.5"
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]
